
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)

add_compile_options("-g")
add_link_options("-g")

option(SANITIZER_ADDRESS "Enable address sanitizer" OFF)
option(SANITIZER_MEMORY "Enable memory sanitizer" OFF)
option(SANITIZER_THREAD "Enable thread sanitizer" OFF)
option(SANITIZER_UB "Enable undefined-behavior sanitizer" OFF)

set(SANITIZER_LIST "")
if(SANITIZER_ADDRESS)
  list(APPEND SANITIZER_LIST "address")
endif()
if(SANITIZER_MEMORY)
  if(SANITIZER_ADDRESS)
    message(FATAL_ERROR "Cannot enable both address and memory sanitizers simultaneously")
  endif()
  list(APPEND SANITIZER_LIST "memory")
endif()
if(SANITIZER_THREAD)
  list(APPEND SANITIZER_LIST "thread")
endif()
if(SANITIZER_UB)
  list(APPEND SANITIZER_LIST "undefined")
endif()
string(REPLACE ";" "," SANITIZER_LIST_STRING "${SANITIZER_LIST}")
if(SANITIZER_LIST_STRING)
  set(SANITIZER_STRING "-fsanitize=${SANITIZER_LIST_STRING}")
  add_compile_options(${SANITIZER_STRING})
  link_libraries(${SANITIZER_STRING})
else()
  set(SANITIZER_STRING "")
endif()

string(TOLOWER "${CMAKE_BUILD_TYPE}" BUILD_TYPE)
if(BUILD_TYPE STREQUAL "debug")
  add_compile_options("-Wall" "-Werror")
elseif(BUILD_TYPE STREQUAL "release")
  add_compile_options("-march=native")
endif()
